report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
configfile: "config.yaml"

rule all:
    input: ["output/Observational.csv", "output/MR_aggregate.csv"]

rule obs_analysis:
    input:
        "input/data_Observational.csv"
    output:
        "output/Observational.csv"
    conda:
        "envs/cvd1-inf1-hf.yaml"
    script:
        "scripts/Obs_analysis.R"

rule MR_analysis:
    input:
        data_MR="input/data_MR.csv",
        ldrho="input/cis200kb_ldrho/{protein}.ld",
        snplist="input/cis200kb_ldrho/{protein}.snplist"
    conda:
        "envs/cvd1-inf1-hf.yaml"
    output:
        "output/MR/{protein}.csv"
    script:
        "scripts/MR_analysis.R"

rule aggregate_MR:
    input:
        expand("output/MR/{protein}.csv", protein = config["target_protein_MR"])
    output:
        "output/MR_aggregate.csv"
    shell:
        "awk 'NR == FNR {{print; next}} FNR > 1 {{print}}' {input} > {output}"
