report: "report/workflow.rst"

# Allow users to fix the underlying OS via singularity.
configfile: "config.yaml"

rule all:
    input: ["output/Obs.csv", "output/MR.csv"]

rule obs_analysis:
    input:
        "input/Obs.csv"
    output:
        "output/Obs.csv"
    conda:
        "envs/cvd1-inf1-hf.yaml"
    script:
        "r/Obs_analysis.R"

rule MR_analysis:
    input:
        data_MR="input/MR.csv",
        ldrho="input/ld/{protein}.ld",
        snplist="input/ld/{protein}.snplist"
    conda:
        "envs/cvd1-inf1-hf.yaml"
    output:
        "output/MR/{protein}.csv"
    script:
        "r/MR_analysis.R"

rule aggregate_MR:
    input:
        expand("output/MR/{protein}.csv", protein = config["target_protein_MR"])
    output:
        "output/MR.csv"
    shell:
        "awk 'NR == FNR {{print; next}} FNR > 1' {input} > {output}"
