options(width=200)
library(gap)
load("biomaRt.rda")
v <- c("ensembl_gene_id","chromosome_name","start_position","end_position","hgnc_symbol","uniprotswissprot")
FGF5_CD6 <- unique(subset(biomaRt[v],hgnc_symbol%in%c("FGF5","CD6")))
FGF5_CD6["uniprotswissprot"] <- with(subset(inf1,gene%in%c("FGF5","CD6")),uniprot)
s <- unique(subset(biomaRt[v],uniprotswissprot%in%inf1$uniprot))
inf1 <- merge(inf1,rbind(s,FGF5_CD6)[c("ensembl_gene_id","uniprotswissprot")],by.x="uniprot",by.y="uniprotswissprot")
inf1[with(inf1,uniprot)%in%c("Q8NF90","Q8WWJ7"),"uniprot"] <- c("P12034","P30203")
save(inf1,file="inf1.rda",compress='xz')
